version: '3'

services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - ./:/app
    environment:
      - HOST_ADDRESS=172.22.0.1
    networks:
      - kafka_network

networks:
  kafka_network:
    external: true